### ISSUE TITLE
Installed cron `keymaker-group-sync` fails on adding user to group

### ISSUE THREAD

**Issue by laroo** [kislyuk/keymaker#21] opened 2017-07-04 14:08 UTC
The automatically installed cron `/etc/cron.d/keymaker-group-sync` fails when it needs to add a user to a group:

```
INFO:keymaker:Syncing IAM group keymaker_mynewgroup
WARNING:keymaker:User myuser1 is not provisioned or not managed by keymaker, skipping
INFO:keymaker:Adding user myuser2 to group sudo
Traceback (most recent call last):
  File "/usr/local/bin/keymaker", line 89, in <module>
    locals()[args.command](args)
  File "/usr/local/lib/python2.7/dist-packages/keymaker/__init__.py", line 240, in sync_groups
    subprocess.check_call(["usermod", "--append", "--groups", unix_group_name, user])
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Problem is that the $PATH variable is not set. Current solution is to set the variable manually (used /etc/environment):

```
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
*/5 * * * * root /usr/local/bin/keymaker sync_groups
```

The cron would have probably also failed on the other commands used by sync_groups: `groupadd` and `gpasswd`. By setting the PATH these commands should work as well.

My environment details:
Keymaker: 0.4.3
Distribution: Ubuntu 14.04.5 LTS
Kernel: Linux 3.13.0-112-generic #159-Ubuntu

**Comment by rscottthreewiresyscom** [comment] 2018-03-08 17:35
Just to add this this, the PATH variable worked for me as well on RHEL7.

**Comment by jbergknoff-rival** [comment] 2019-09-26 18:37
Same situation on Ubuntu 18.04

**Comment by kislyuk** [comment] 2019-09-28 14:36
Thank you for persisting in reporting this. I originally overlooked this issue and I agree that it should be fixed.

I'm thinking of running `source /etc/profile` instead of setting `$PATH` directly. Any objections to this?

**Closed** 2019-09-30 05:15 UTC

**Comment by kislyuk** [comment] 2019-09-30 17:59
My system's stock `/etc/crontab` on Ubuntu 18.04 sets its PATH correctly. I am unable to reproduce this problem. I am going to revert 05cc758 because I'm not sure where this problem comes from - if one of the reporters can provide the version of the cron daemon and steps to reproduce this with a clean install, I can look into this further.

My guess is that you are incorrectly changing your `/etc/crontab` to remove the `PATH` setting from it.

**Comment by jbergknoff-rival** [comment] 2019-10-14 18:30
Sorry I didn't respond earlier. This problem can be reproduced using a stock Ubuntu 18.04 AMI in EC2, i.e. those provided by Canonical here: https://cloud-images.ubuntu.com/locator/ec2/.
